// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnXjORgJve6LnXMQqG2kUDGWuuYeTbb0I',
    appId: '1:1043515983877:web:ebde4f706f4f185434346c',
    messagingSenderId: '1043515983877',
    projectId: 'drinking-coffee-8eb88',
    authDomain: 'drinking-coffee-8eb88.firebaseapp.com',
    storageBucket: 'drinking-coffee-8eb88.firebasestorage.app',
    measurementId: 'G-RDC9VKB32X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBefTZly-Wl-I1ezZFCf49UVLGNwqbAyAQ',
    appId: '1:1043515983877:android:1e600849ec8518dd34346c',
    messagingSenderId: '1043515983877',
    projectId: 'drinking-coffee-8eb88',
    storageBucket: 'drinking-coffee-8eb88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDve5KCBv_x1Pm85RkUec8k_8D2cpPXhBY',
    appId: '1:1043515983877:ios:418dffed7ec70a8034346c',
    messagingSenderId: '1043515983877',
    projectId: 'drinking-coffee-8eb88',
    storageBucket: 'drinking-coffee-8eb88.firebasestorage.app',
    iosClientId: '1043515983877-ipec38ce4os1peom2tkj937g3e3dh69r.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDve5KCBv_x1Pm85RkUec8k_8D2cpPXhBY',
    appId: '1:1043515983877:ios:418dffed7ec70a8034346c',
    messagingSenderId: '1043515983877',
    projectId: 'drinking-coffee-8eb88',
    storageBucket: 'drinking-coffee-8eb88.firebasestorage.app',
    iosClientId: '1043515983877-ipec38ce4os1peom2tkj937g3e3dh69r.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnXjORgJve6LnXMQqG2kUDGWuuYeTbb0I',
    appId: '1:1043515983877:web:c740ea9879a19cfc34346c',
    messagingSenderId: '1043515983877',
    projectId: 'drinking-coffee-8eb88',
    authDomain: 'drinking-coffee-8eb88.firebaseapp.com',
    storageBucket: 'drinking-coffee-8eb88.firebasestorage.app',
    measurementId: 'G-8G8JLXVDJF',
  );
}
